FROM nginx:1.15-alpine
ENV NSS_SDB_USE_CACHE YES
RUN apk add nss-dev tzdata

ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_KR.UTF-8
ENV LC_ALL zh_KR.UTF-8
ENV TZ=Asia/Seoul

RUN apk --update add tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime && \
    apk del tzdata && \
    rm -rf /var/cache/apk/*