apiVersion: v1
kind: Service
metadata:
  labels:
    app: was-server
  name: was-server
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: was-server
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 30
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: was-server
  name: was-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: was-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: was-server
    spec:
      containers:
      - env:
        - name: DB_USER
          value: acloud
        - name: DB_PASSWORD
          value: Acloud(2020!@)
        - name: DB_URL
          value: jdbc:mariadb://demo-db:3306/acloud?useUnicode=true&charaterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        image: regi.acloud.run/library/was-server:dev-local
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/check/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: was-server
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/check/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 50
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: "2147483648"
          requests:
            cpu: 500m
            memory: "1073741824"
        securityContext:
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30