/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

USE `acloud`;

/*!40000 ALTER TABLE `codes` DISABLE KEYS */;
INSERT INTO `codes` (`code_group_id`, `code`, `value`, `description`, `sort_order`, `use_yn`) VALUES
	('COCKTAIL_CONFIG', 'RESOURCE_PREFIX', LEFT(TO_BASE64(SHA(RAND())), 6), '', 0, 'Y'),
	('ACCESS_MODE', 'ROX', 'ReadOnlyMany', '', 1, 'Y'),
	('ACCESS_MODE', 'RWO', 'ReadWriteOnce', '', 0, 'Y'),
	('ACCESS_MODE', 'RWX', 'ReadWriteMany', '', 2, 'Y'),
	('ACCOUNT_USE_TYPE', 'ADMIN', 'Admin', '', 3, 'Y'),
	('ACCOUNT_USE_TYPE', 'METERING', 'Metering', '', 4, 'Y'),
	('ACCOUNT_USE_TYPE', 'USER', 'User', '', 2, 'Y'),
	('AUTH_TYPE', 'CERT', 'X.509', '', 3, 'Y'),
	('AUTH_TYPE', 'TOKEN', 'Token base auth', '', 2, 'Y'),
	('AUTH_TYPE', 'PLAIN', 'id & password base auth', '', 1, 'Y'),
	('AWS_CSERVER', 'MULTI', 'Multi', '', 2, 'Y'),
	('AWS_CSERVER', 'SINGLE', 'Single', '', 1, 'Y'),
	('AWS_LB_POLICY', 'APP_COOKIE_STICKINESS', 'Application Cookie Stickiness', '', 3, 'Y'),
	('AWS_LB_POLICY', 'LB_COOKIE_STICKINESS', 'Loadbalancer Cookie Stickiness', '', 2, 'Y'),
	('AWS_LB_POLICY', 'ROUND_ROBIN', 'Round Robin', '', 1, 'Y'),
	('AWS_REGION', 'us-east-1', 'N. Virginia', 'US East (N. Virginia)', 0, 'Y'),
	('AWS_REGION', 'us-east-2', 'Ohio', 'US East (Ohio)', 0, 'Y'),
	('AWS_REGION', 'us-west-1', 'N. California', 'US West (N. California)', 0, 'Y'),
	('AWS_REGION', 'us-west-2', 'Oregon', 'US West (Oregon)', 0, 'Y'),
	('AWS_REGION', 'ca-central-1', 'Central', 'Canada (Central)', 0, 'Y'),
	('AWS_REGION', 'eu-central-1', 'Frankfurt', 'EU (Frankfurt)', 0, 'Y'),
	('AWS_REGION', 'eu-west-1', 'Ireland', 'EU (Ireland)', 0, 'Y'),
	('AWS_REGION', 'eu-west-2', 'London', 'EU (London)', 0, 'Y'),
	('AWS_REGION', 'eu-west-3', 'Paris', 'EU (Paris)', 0, 'Y'),
	('AWS_REGION', 'ap-northeast-1', 'Tokyo', 'Asia Pacific (Tokyo)', 0, 'Y'),
	('AWS_REGION', 'ap-northeast-2', 'Seoul', 'Asia Pacific (Seoul)', 0, 'Y'),
	('AWS_REGION', 'ap-northeast-3', 'Osaka-Local', 'Asia Pacific (Osaka-Local)', 0, 'Y'),
	('AWS_REGION', 'ap-southeast-1', 'Singapore', 'Asia Pacific (Singapore)', 0, 'Y'),
	('AWS_REGION', 'ap-southeast-2', 'Sydney', 'Asia Pacific (Sydney)', 0, 'Y'),
	('AWS_REGION', 'ap-south-1', 'Mumbai', 'Asia Pacific (Mumbai)', 0, 'Y'),
	('AWS_REGION', 'sa-east-1', 'São Paulo', 'South America (São Paulo)', 0, 'Y'),
	('GCP_REGION', 'northamerica-northeast1', 'Montréal', 'Montréal, Canada - (northamerica-northeast1-a, northamerica-northeast1-b, northamerica-northeast1-c)', 0, 'Y'),
	('GCP_REGION', 'us-central1', 'Iowa', 'Council Bluffs, Iowa, USA - (us-central1-a, us-central1-b, us-central1-c, us-central1-f)', 0, 'Y'),
	('GCP_REGION', 'us-west1', 'Oregon', 'The Dalles, Oregon, USA - (us-west1-a, us-west1-b, us-west1-c)', 0, 'Y'),
	('GCP_REGION', 'us-west2', 'Los Angeles', 'Los Angeles, California, USA - (us-west2-a, us-west2-b, us-west2-c)', 0, 'Y'),
	('GCP_REGION', 'us-east1', 'South Carolina', 'Moncks Corner, South Carolina, USA - (us-east1-b, us-east1-c, us-east1-d)', 0, 'Y'),
	('GCP_REGION', 'us-east4', 'Northern Virginia', 'Ashburn, Virginia, USA - (us-east4-a, us-east4-b, us-east4-c)', 0, 'Y'),
	('GCP_REGION', 'southamerica-east1', 'São Paulo', 'São Paulo, Brazil - (southamerica-east1-a, southamerica-east1-b, southamerica-east1-c)', 0, 'Y'),
	('GCP_REGION', 'europe-north1', 'Hamina', 'Hamina, Finland - (europe-north1-a, europe-north1-c, europe-north1-b)', 0, 'Y'),
	('GCP_REGION', 'europe-west1', 'Belgium', 'St. Ghislain, Belgium - (europe-west1-b, europe-west1-c, europe-west1-d)', 0, 'Y'),
	('GCP_REGION', 'europe-west2', 'London', 'London, U.K. - (europe-west2-a, europe-west2-b, europe-west2-c)', 0, 'Y'),
	('GCP_REGION', 'europe-west3', 'Frankfurt', 'Frankfurt, Germany - (europe-west3-a, europe-west3-b, europe-west3-c)', 0, 'Y'),
	('GCP_REGION', 'europe-west4', 'Netherlands', 'Eemshaven, Netherlands - (europe-west4-a, europe-west4-b, europe-west4-c)', 0, 'Y'),
	('GCP_REGION', 'europe-west6', 'Zürich', 'Zürich, Switzerland - (europe-west6-a, europe-west6-b, europe-west6-c)', 0, 'Y'),
	('GCP_REGION', 'asia-south1', 'Mumbai', 'Mumbai, India - (asia-south1-a, asia-south1-b, asia-south1-c)', 0, 'Y'),
	('GCP_REGION', 'asia-southeast1', 'Singapore', 'Jurong West, Singapore - (asia-southeast1-a, asia-southeast1-b)', 0, 'Y'),
	('GCP_REGION', 'asia-east1', 'Taiwan', 'Changhua County, Taiwan - (asia-east2-a, asia-east2-b, asia-east2-c)', 0, 'Y'),
	('GCP_REGION', 'asia-east2', 'Hong Kong', 'Hong Kong - (asia-east1-a, asia-east1-b, asia-east1-c)', 0, 'Y'),
	('GCP_REGION', 'asia-northeast1', 'Tokyo', 'Tokyo, Japan - (asia-northeast1-a, asia-northeast1-b, asia-northeast1-c)', 0, 'Y'),
	('GCP_REGION', 'asia-northeast2', 'Osaka', 'Osaka, Japan - (asia-northeast2-a, asia-northeast2-b, asia-northeast2-c)', 0, 'Y'),
	('GCP_REGION', 'asia-northeast3', 'Seoul', 'Seoul, South Korea - (asia-northeast3-a, asia-northeast3-b, asia-northeast3-c)', 0, 'Y'),
	('GCP_REGION', 'australia-southeast1', 'Sydney', 'Sydney, Australia - (australia-southeast1-a, australia-southeast1-b, australia-southeast1-c)', 0, 'Y'),
	('AZR_REGION', 'westus', 'California', 'West US - region Americas', 0, 'Y'),
	('AZR_REGION', 'westus2', 'Washington', 'West US 2 - region Americas', 0, 'Y'),
	('AZR_REGION', 'centralus', 'Iowa', 'Central US - region Americas', 0, 'Y'),
	('AZR_REGION', 'eastus', 'Virginia', 'East US - region Americas', 0, 'Y'),
	('AZR_REGION', 'eastus2', 'Virginia2', 'East US 2 - region Americas', 0, 'Y'),
	('AZR_REGION', 'northcentralus', 'Illinois', 'North Central US - region Americas', 0, 'Y'),
	('AZR_REGION', 'southcentralus', 'Texas', 'South Central US - region Americas', 0, 'Y'),
	('AZR_REGION', 'westcentralus', 'Wyoming', 'West Central US - region Americas', 0, 'Y'),
	('AZR_REGION', 'canadacentral', 'Toronto', 'Canada Central - region Americas', 0, 'Y'),
	('AZR_REGION', 'canadaeast', 'Quebec City', 'Canada East - region Americas', 0, 'Y'),
	('AZR_REGION', 'brazilsouth', 'Sao Paulo State', 'Brazil South - region Americas', 0, 'Y'),
	('AZR_REGION', 'northeurope', 'Ireland', 'North Europe - region Europe', 0, 'Y'),
	('AZR_REGION', 'westeurope', 'Netherlands', 'West Europe - region Europe', 0, 'Y'),
	('AZR_REGION', 'uksouth', 'London', 'UK South - region Europe', 0, 'Y'),
	('AZR_REGION', 'ukwest', 'Cardiff', 'UK West - region Europe', 0, 'Y'),
	('AZR_REGION', 'eastasia', 'Hong Kong', 'East Asia - region Asia', 0, 'Y'),
	('AZR_REGION', 'southeastasia', 'Singapore', 'Southeast Asia - region Asia', 0, 'Y'),
	('AZR_REGION', 'japaneast', 'Tokyo, Saitama', 'Japan East - region Asia', 0, 'Y'),
	('AZR_REGION', 'japanwest', 'Osaka', 'Japan West - region Asia', 0, 'Y'),
	('AZR_REGION', 'australiaeast', 'New South Wales', 'Australia East - region Asia', 0, 'Y'),
	('AZR_REGION', 'australiasoutheast', 'Victoria', 'Australia Southeast - region Asia', 0, 'Y'),
	('AZR_REGION', 'centralindia', 'Pune', 'Central India - region Asia', 0, 'Y'),
	('AZR_REGION', 'southindia', 'Chennai', 'South India - region Asia', 0, 'Y'),
	('AZR_REGION', 'westindia', 'Mumbai', 'West India - region Asia', 0, 'Y'),
	('AZR_REGION', 'koreasouth', 'Busan', 'Korea South - region Asia', 0, 'Y'),
	('AZR_REGION', 'koreacentral', 'Seoul', 'Korea Central - region Asia', 0, 'Y'),
	('AZR_REGION', 'chinanorth', 'Beijing', 'China North - region China', 0, 'Y'),
	('AZR_REGION', 'chinaeast', 'Shanghai', 'China East - region China', 0, 'Y'),
	('AZR_REGION', 'germanycentral', 'Frankfurt', 'Germany Central - region German', 0, 'Y'),
	('AZR_REGION', 'germanynortheast', 'Magdeburg', 'Germany Northeast - region German', 0, 'Y'),
	('ABC_REGION', 'cn-hongkong', 'Hong Kong', 'Hong Kong, Hong Kong', 0, 'Y'),
	('ABC_REGION', 'ap-southeast-1', 'Singapore', 'Singapore, Asia Pacific SE 1', 0, 'Y'),
	('ABC_REGION', 'ap-southeast-2', 'Sydney', 'Sydney, Asia Pacific SE 2', 0, 'Y'),
	('ABC_REGION', 'ap-southeast-3', 'Kuala Lumpur', 'Kuala Lumpur, Asia Pacific SE 3', 0, 'Y'),
	('ABC_REGION', 'ap-southeast-5', 'Jakarta', 'Jakarta, Asia Pacific SE 5', 0, 'Y'),
	('ABC_REGION', 'ap-south-1', 'Mumbai', 'Mumbai , Asia Pacific SOU 1', 0, 'Y'),
	('ABC_REGION', 'ap-northeast-1', 'Tokyo', 'Tokyo, Asia Pacific NE 1', 0, 'Y'),
	('ABC_REGION', 'us-west-1', 'Silicon Valley', 'Silicon Valley, US West 1', 0, 'Y'),
	('ABC_REGION', 'us-east-1', 'Virginia', 'Virginia, US East 1', 0, 'Y'),
	('ABC_REGION', 'eu-central-1', 'Frankfurt', 'Frankfurt, EU Central 1', 0, 'Y'),
	('ABC_REGION', 'eu-west-1', 'London', 'London, UK (London)', 0, 'Y'),
	('ABC_REGION', 'me-east-1', 'Dubai', 'Dubai, Middle East 1', 0, 'Y'),
	('ABC_REGION', 'cn-qingdao', 'Qingdao', 'Qingdao, China North 1', 0, 'Y'),
	('ABC_REGION', 'cn-beijing', 'Beijing', 'Beijing, China North 2', 0, 'Y'),
	('ABC_REGION', 'cn-zhangjiakou', 'Zhangjiakou', 'Zhangjiakou, China North 3', 0, 'Y'),
	('ABC_REGION', 'cn-huhehaote', 'Hohhot', 'Hohhot, China North 5', 0, 'Y'),
	('ABC_REGION', 'cn-hangzhou', 'Hangzhou', 'Hangzhou, China East 1', 0, 'Y'),
	('ABC_REGION', 'cn-shanghai', 'Shanghai', 'Shanghai, China East 2', 0, 'Y'),
	('ABC_REGION', 'cn-shenzhen', 'Shenzhen', 'Shenzhen, China South 1', 0, 'Y'),
	('TCC_REGION', 'ap-beijing-1', 'Beijiing Zone 1 (North China)', 'Beijiing Zone 1 (North China)', 0, 'Y'),
	('TCC_REGION', 'ap-beijing', 'Beijing', 'Beijing', 0, 'Y'),
	('TCC_REGION', 'ap-shanghai', 'Shanghai (East China)', 'Shanghai (East China)', 0, 'Y'),
	('TCC_REGION', 'ap-guangzhou', 'Guangzhou (South China)', 'Guangzhou (South China)', 0, 'Y'),
	('TCC_REGION', 'ap-chengdu', 'Chengdu (Southwest China)', 'Chengdu (Southwest China)', 0, 'Y'),
	('TCC_REGION', 'ap-singapore', 'Singapore', 'Singapore', 0, 'Y'),
	('TCC_REGION', 'ap-hongkong', 'Hong Kong', 'Hong Kong', 0, 'Y'),
	('TCC_REGION', 'na-toronto', 'Toronto', 'Toronto', 0, 'Y'),
	('TCC_REGION', 'eu-frankfurt', 'Frankfurt', 'Frankfurt', 0, 'Y'),
	('TCC_REGION', 'ap-mumbai', 'Mumbai', 'Mumbai', 0, 'Y'),
	('TCC_REGION', 'ap-seoul', 'Seoul', 'Seoul', 0, 'Y'),
	('TCC_REGION', 'na-siliconvalley', 'Silicon Valley', 'Silicon Valley', 0, 'Y'),
	('TCC_REGION', 'na-ashburn', 'Virginia', 'Virginia', 0, 'Y'),
	('TCC_REGION', 'ap-bangkok', 'Bangkok', 'Bangkok', 0, 'Y'),
	('TCC_REGION', 'eu-moscow', 'Moscow', 'Moscow', 0, 'Y'),
	('TCC_REGION', 'ap-tokyo', 'Tokyo', 'Tokyo', 0, 'Y'),
	('COLOR', 'blue', '', 'yellow', 0, 'Y'),
	('COLOR', 'green', '', 'green', 0, 'Y'),
	('CSERVER_TYPE', 'AWS', 'AWS_CSERVER', '', 1, 'Y'),
	('CSERVER_TYPE', 'K8S', 'KUBE_CSERVER', '', 2, 'Y'),
	('CUBE_TYPE', 'MANAGED', 'Managed', 'Kuberbetes Cluster in AWS, Baremetal', 1, 'Y'),
	('CUBE_TYPE', 'PROVIDER', 'Provider', 'Kuberbetes Cluster in Cloud, With provisioning service, Baremetal', 2, 'Y'),
	('CUBE_TYPE', 'ACS', 'ACS', 'Kuberbetes Cluster in Azure Container Service', 3, 'N'),
	('CUBE_TYPE', 'AKS', 'AKS', 'Kuberbetes Cluster in Azure Kuberbetes Service', 4, 'Y'),
	('CUBE_TYPE', 'ECS', 'ECS', 'Kuberbetes Cluster in AWS Container Service', 5, 'N'),
	('CUBE_TYPE', 'EKS', 'EKS', 'Kuberbetes Cluster in AWS Kuberbetes Service', 6, 'Y'),
	('CUBE_TYPE', 'GKE', 'GKE', 'Kuberbetes Cluster in Googke Kuberbetes Engine', 7, 'Y'),
	('CUBE_TYPE', 'TKE', 'TKE', 'Kuberbetes Cluster in Tencent Kuberbetes Engine', 8, 'Y'),
	('IDC_REGION', 'DEFAULT', 'Default', '', 0, 'Y'),
	('KUBE_CSERVER', 'MULTI', 'Multi', '', 0, 'Y'),
	('LANGUAGE', 'ko', 'Korean', 'Korean', 1, 'Y'),
	('LANGUAGE', 'zh', 'Chinese', 'Chinese', 2, 'Y'),
	('LANGUAGE', 'en', 'English', 'English', 3, 'Y'),
	('LANGUAGE', 'ja', 'Japanese', 'Japanese', 4, 'Y'),
	('LB_POLICY_TYPE', 'AWS', 'AWS_LB_POLICY', '', 1, 'Y'),
	('METERING_RESOURCE', 'EBS', 'EBS', 'Elastic Block Store', 0, 'Y'),
	('METERING_RESOURCE', 'EC2_INSTANCE', 'EC2 instance', 'Elastic Compute Cloud Instance', 0, 'Y'),
	('METERING_RESOURCE', 'ELB', 'ELB', 'Elastic Load Balancing', 0, 'Y'),
	('METERING_RESOURCE', 'RDS', 'RDS', 'Relational Database Service', 0, 'Y'),
	('METERING_RESOURCE', 'S3', 'S3', 'Simple Storage Service', 0, 'Y'),
	('OPM_REGION', 'DEFAULT', 'Default', '', 0, 'Y'),
	('PORT_TYPE', 'CLUSTER_IP', 'ClusterIP', '', 1, 'Y'),
	('PORT_TYPE', 'INTERNAL', 'Internal', '', 0, 'Y'),
	('PORT_TYPE', 'LOADBALANCER', 'LoadBalancer', '', 3, 'Y'),
	('PORT_TYPE', 'NODE_PORT', 'NodePort', '', 2, 'Y'),
	('PROTOCOL', 'ALL', '', '', 0, 'Y'),
	('PROTOCOL', 'ICMP', '', '', 0, 'Y'),
	('PROTOCOL', 'TCP', '', '', 0, 'Y'),
	('PROTOCOL', 'UDP', '', '', 0, 'Y'),
	('PROVIDER', 'AWS', 'Amazon Web Service', 'Amazon Web Service', 0, 'Y'),
	('PROVIDER', 'GCP', 'Google Cloud Platform', 'Google Cloud Platform', 1, 'Y'),
	('PROVIDER', 'AZR', 'Microsoft Azure', 'Microsoft Azure', 2, 'Y'),
	('PROVIDER', 'ABC', 'Alibaba Cloud', 'Alibaba Cloud', 3, 'Y'),
	('PROVIDER', 'TCC', 'Tencent Cloud', 'Tencent Cloud', 4, 'Y'),
	('PROVIDER', 'RVS', 'Rovius Cloud', 'Rovius Cloud', 5, 'Y'),
	('PROVIDER', 'OPM', 'On-Premise', 'On-Premise', 6, 'Y'),
	('PROVIDER', 'IDC', 'Datacenter', 'Datacenter', 7, 'Y'),
	('REGION_GROUP', 'AWS', 'AWS_REGION', '', 0, 'Y'),
	('REGION_GROUP', 'AZR', 'AZR_REGION', '', 0, 'Y'),
	('REGION_GROUP', 'GCP', 'GCP_REGION', '', 0, 'Y'),
	('REGION_GROUP', 'ABC', 'ABC_REGION', '', 0, 'Y'),
	('REGION_GROUP', 'TCC', 'TCC_REGION', '', 0, 'Y'),
	('SECURITY_TYPE', 'IN_BOUND', '', 'inbound rule', 0, 'Y'),
	('SECURITY_TYPE', 'OUT_BOUND', '', 'outbound rule', 0, 'Y'),
	('SERVER_TYPE', 'DAEMON_SET', 'Daemon Set', 'K8S Daemon Set', 0, 'Y'),
	('SERVER_TYPE', 'JOB', 'Job', 'K8S Job', 0, 'Y'),
	('SERVER_TYPE', 'MULTI', 'Multi-instance', 'Multi instance server', 0, 'Y'),
	('SERVER_TYPE', 'SINGLE', 'Single-instance', 'Single instance server', 0, 'Y'),
	('SERVER_TYPE', 'STATEFUL_SET', 'Statefull Set', 'K8S Statefull Set', 0, 'Y'),
	('SUBNET_TYPE', 'COCKTAIL', 'Cocktail', 'Cocktail Cluster', 0, 'Y'),
	('SUBNET_TYPE', 'CUBE', 'Cube', 'Cube Cluster', 1, 'Y'),
	('USER_ROLE', 'ADMIN', 'Administrator', 'System Administrator', 1, 'Y'),
	('USER_ROLE', 'SYSTEM', 'System Manager', 'System Manager', 2, 'Y'),
	('USER_ROLE', 'SYSUSER', 'System User', 'System User', 3, 'Y'),
	('USER_ROLE', 'DEVOPS', 'DevOps', 'DevOps', 4, 'Y'),
	('VOLUME_ACCESS_MODE', 'ROX', 'ReadOnlyMany', 'Read Only Many', 1, 'Y'),
	('VOLUME_ACCESS_MODE', 'RWO', 'ReadWriteOnce', 'Read Write Once', 0, 'Y'),
	('VOLUME_ACCESS_MODE', 'RWX', 'ReadWriteMany', 'Read Write Many', 2, 'Y'),
	('VOLUME_PHASES', 'AVAILABLE', 'Available', 'Available', 0, 'Y'),
	('VOLUME_PHASES', 'BOUND', 'Bound', 'Bound', 1, 'Y'),
	('VOLUME_PHASES', 'FAILED', 'Failed', 'Failed', 3, 'Y'),
	('VOLUME_PHASES', 'RELEASED', 'Released', 'Relaesed', 2, 'Y'),
	('VOLUME_PLUGIN', 'AWSEBS', 'awsElasticBlockStore', 'AWS EBS', 1, 'Y'),
	('VOLUME_PLUGIN', 'AWSEFS', 'awsElasticFileSystem', 'AWS EFS', 2, 'Y'),
	('VOLUME_PLUGIN', 'GCE', 'gcePersistentDisk', 'Google Persistent Disk', 3, 'Y'),
	('VOLUME_PLUGIN', 'AZUREDISK', 'azureDisk', 'Azure Disk', 4, 'Y'),
	('VOLUME_PLUGIN', 'AZUREFILE', 'azureFile', 'Azure File', 5, 'Y'),
	('VOLUME_PLUGIN', 'NFSDYNAMIC', 'nfsDynamicVolume', 'NFS', 6, 'Y'),
	('VOLUME_PLUGIN', 'NFSSTATIC', 'nfsStaticVolume', 'NFS Named', 7, 'Y'),
	('VOLUME_PLUGIN', 'GFS', 'glusterfs', 'Glusterfs', 8, 'N'),
	('VOLUME_RECLAIM_POLICY', 'DELETE', 'Delete', 'Delete', 2, 'Y'),
	('VOLUME_RECLAIM_POLICY', 'RECYCLE', 'Recycle', 'Recycle', 1, 'Y'),
	('VOLUME_RECLAIM_POLICY', 'RETAIN', 'Retain', 'Retain', 0, 'Y'),
	('VOLUME_TYPE', 'CONFIG_MAP', 'ConfigMap', '', 4, 'Y'),
	('VOLUME_TYPE', 'EMPTY_DIR', 'EmptyDir', '', 2, 'Y'),
	('VOLUME_TYPE', 'HOST_PATH', 'HostPath', '', 1, 'Y'),
	('VOLUME_TYPE', 'None', 'None', '', 0, 'Y'),
	('VOLUME_TYPE', 'PERSISTENT_VOLUME_LINKED', 'PersistentVolume Linked', '', 6, 'Y'),
	('VOLUME_TYPE', 'PERSISTENT_VOLUME_STATIC', 'PersistentVolume', '', 5, 'Y'),
	('VOLUME_TYPE', 'PERSISTENT_VOLUME', 'Dynamic PV Config', '', 3, 'Y'),
	('PERSISTENT_VOLUME_TYPE', 'SINGLE', 'Single Persistent Volume Type', 'Only ReadWriteOnce Supports Storage', 1, 'Y'),
	('PERSISTENT_VOLUME_TYPE', 'SHARED', 'Shared Persistent Volume Type', 'ReadOnlyMany or ReadWriteMany Supports Storage', 2, 'Y'),
	('STORAGE_TYPE', 'BLOCK', 'Block', 'AWS-EBS, GCE-PD, Azure-Disk, Azure-File', 1, 'Y'),
	('STORAGE_TYPE', 'NETWORK', 'Network', 'NFS(Named), AWS-EFS', 2, 'Y'),
	('CLUSTER_STATE', 'RUNNING', 'Running', 'Cluster State is running.', 1, 'Y'),
	('CLUSTER_STATE', 'STOPPED', 'Stopped', 'Cluster State is stopped.', 2, 'Y'),
	('AWS_EC_TYPE','t3.medium','2 vCPU / 8G memory','AWS_EC_TYPE_t3.medium',1, 'Y'),
	('AWS_EC_TYPE','t3.large','2 vCPU / 16G memory','AWS_EC_TYPE_t3.large',2, 'Y'),
	('AWS_EC_TYPE','t3.xlarge','4 vCPU / 32G memory','AWS_EC_TYPE_t3.xlarge',3, 'Y'),
	('AWS_EC_TYPE','t3.2xlarge','8 vCPU / 0.5G memory','AWS_EC_TYPE_t3.2xlarge',4, 'Y'),
	('AWS_EC_TYPE','t2.nano','1 vCPU / 1G memory','AWS_EC_TYPE_t2.nano',5, 'Y'),
	('AWS_EC_TYPE','t2.micro','1 vCPU / 2G memory','AWS_EC_TYPE_t2.micro',6, 'Y'),
	('AWS_EC_TYPE','t2.small','1 vCPU / 4G memory','AWS_EC_TYPE_t2.small',7, 'Y'),
	('AWS_EC_TYPE','t2.medium','2 vCPU / 8G memory','AWS_EC_TYPE_t2.medium',8, 'Y'),
	('AWS_EC_TYPE','t2.large','2 vCPU / 16G memory','AWS_EC_TYPE_t2.large',9, 'Y'),
	('AWS_EC_TYPE','t2.xlarge','4 vCPU / 32G memory','AWS_EC_TYPE_t2.xlarge',10, 'Y'),
	('AWS_EC_TYPE','t2.2xlarge','8 vCPU / 8G memory','AWS_EC_TYPE_t2.2xlarge',11, 'Y'),
	('AWS_EC_TYPE','m5.large','2 vCPU / 16G memory','AWS_EC_TYPE_m5.large',12, 'Y'),
	('AWS_EC_TYPE','m5.xlarge','4 vCPU / 32G memory','AWS_EC_TYPE_m5.xlarge',13, 'Y'),
	('AWS_EC_TYPE','m5.2xlarge','8 vCPU / 64G memory','AWS_EC_TYPE_m5.2xlarge',14, 'Y'),
	('AWS_EC_TYPE','m5.4xlarge','16 vCPU / 192G memory','AWS_EC_TYPE_m5.4xlarge',15, 'Y'),
	('AWS_EC_TYPE','m5.12xlarge','48 vCPU / 384G memory','AWS_EC_TYPE_m5.12xlarge',16, 'Y'),
	('AWS_EC_TYPE','m5.24xlarge','96 vCPU / 8G memory','AWS_EC_TYPE_m5.24xlarge',17, 'Y'),
	('AWS_EC_TYPE','m5d.large','2 vCPU / 16G memory','AWS_EC_TYPE_m5d.large',18, 'Y'),
	('AWS_EC_TYPE','m5d.xlarge','4 vCPU / 32G memory','AWS_EC_TYPE_m5d.xlarge',19, 'Y'),
	('AWS_EC_TYPE','m5d.2xlarge','8 vCPU / 64G memory','AWS_EC_TYPE_m5d.2xlarge',20, 'Y'),
	('AWS_EC_TYPE','m5d.4xlarge','16 vCPU / 192G memory','AWS_EC_TYPE_m5d.4xlarge',21, 'Y'),
	('AWS_EC_TYPE','m5d.12xlarge','48 vCPU / 384G memory','AWS_EC_TYPE_m5d.12xlarge',22, 'Y'),
	('AWS_EC_TYPE','m5d.24xlarge','96 vCPU / 8G memory','AWS_EC_TYPE_m5d.24xlarge',23, 'Y'),
	('AWS_EC_TYPE','m5a.large','2 vCPU / 16G memory','AWS_EC_TYPE_m5a.large',24, 'Y'),
	('AWS_EC_TYPE','m5a.xlarge','4 vCPU / 32G memory','AWS_EC_TYPE_m5a.xlarge',25, 'Y'),
	('AWS_EC_TYPE','m5a.2xlarge','8 vCPU / 64G memory','AWS_EC_TYPE_m5a.2xlarge',26, 'Y'),
	('AWS_EC_TYPE','m5a.4xlarge','16 vCPU / 192G memory','AWS_EC_TYPE_m5a.4xlarge',27, 'Y'),
	('AWS_EC_TYPE','m5a.12xlarge','48 vCPU / 384G memory','AWS_EC_TYPE_m5a.12xlarge',28, 'Y'),
	('AWS_EC_TYPE','m5a.24xlarge','96 vCPU / 8G memory','AWS_EC_TYPE_m5a.24xlarge',29, 'Y'),
	('AWS_EC_TYPE','m4.large','2 vCPU / 16G memory','AWS_EC_TYPE_m4.large',30, 'Y'),
	('AWS_EC_TYPE','m4.xlarge','4 vCPU / 32G memory','AWS_EC_TYPE_m4.xlarge',31, 'Y'),
	('AWS_EC_TYPE','m4.2xlarge','8 vCPU / 64G memory','AWS_EC_TYPE_m4.2xlarge',32, 'Y'),
	('AWS_EC_TYPE','m4.4xlarge','16 vCPU / 160G memory','AWS_EC_TYPE_m4.4xlarge',33, 'Y'),
	('AWS_EC_TYPE','m4.10xlarge','40 vCPU / 256G memory','AWS_EC_TYPE_m4.10xlarge',34, 'Y'),
	('AWS_EC_TYPE','m4.16xlarge','64 vCPU / G memory','AWS_EC_TYPE_m4.16xlarge',35, 'Y'),
	('us-east-1','us-east-1a','us-east-1a','us-east-1_us-east-1a',1, 'Y'),
	('us-east-1','us-east-1b','us-east-1b','us-east-1_us-east-1b',2, 'Y'),
	('us-east-1','us-east-1c','us-east-1c','us-east-1_us-east-1c',3, 'Y'),
	('us-east-1','us-east-1d','us-east-1d','us-east-1_us-east-1d',4, 'Y'),
	('us-east-1','us-east-1e','us-east-1e','us-east-1_us-east-1e',5, 'Y'),
	('us-east-1','us-east-1f','us-east-1f','us-east-1_us-east-1f',6, 'Y'),
	('us-west-2','us-west-2a','us-west-2a','us-west-2_us-west-2a',1, 'Y'),
	('us-west-2','us-west-2b','us-west-2b','us-west-2_us-west-2b',2, 'Y'),
	('us-west-2','us-west-2c','us-west-2c','us-west-2_us-west-2c',3, 'Y'),
	('us-west-1','us-west-1b','us-west-1b','us-west-1_us-west-1b',1, 'Y'),
	('us-west-1','us-west-1c','us-west-1c','us-west-1_us-west-1c',2, 'Y'),
	('eu-west-1','eu-west-1a','eu-west-1a','eu-west-1_eu-west-1a',1, 'Y'),
	('eu-west-1','eu-west-1b','eu-west-1b','eu-west-1_eu-west-1b',2, 'Y'),
	('eu-west-1','eu-west-1c','eu-west-1c','eu-west-1_eu-west-1c',3, 'Y'),
	('eu-central-1','eu-central-1a','eu-central-1a','eu-central-1_eu-central-1a',1, 'Y'),
	('eu-central-1','eu-central-1b','eu-central-1b','eu-central-1_eu-central-1b',2, 'Y'),
	('eu-central-1','eu-central-1c','eu-central-1c','eu-central-1_eu-central-1c',3, 'Y'),
	('ap-southeast-1','ap-southeast-1a','ap-southeast-1a','ap-southeast-1_ap-southeast-1a',1, 'Y'),
	('ap-southeast-1','ap-southeast-1b','ap-southeast-1b','ap-southeast-1_ap-southeast-1b',2, 'Y'),
	('ap-southeast-2','ap-southeast-2a','ap-southeast-2a','ap-southeast-2_ap-southeast-2a',1, 'Y'),
	('ap-southeast-2','ap-southeast-2b','ap-southeast-2b','ap-southeast-2_ap-southeast-2b',2, 'Y'),
	('ap-southeast-2','ap-southeast-2c','ap-southeast-2c','ap-southeast-2_ap-southeast-2c',3, 'Y'),
	('ap-northeast-1','ap-northeast-1a','ap-northeast-1a','ap-northeast-1_ap-northeast-1a',1, 'Y'),
	('ap-northeast-1','ap-northeast-1c','ap-northeast-1c','ap-northeast-1_ap-northeast-1c',2, 'Y'),
	('ap-northeast-2','ap-northeast-2a','ap-northeast-2a','ap-northeast-2_ap-northeast-2a',1, 'Y'),
	('ap-northeast-2','ap-northeast-2c','ap-northeast-2c','ap-northeast-2_ap-northeast-2c',2, 'Y'),
	('sa-east-1','sa-east-1a','sa-east-1a','sa-east-1_sa-east-1a',1, 'Y'),
	('sa-east-1','sa-east-1c','sa-east-1c','sa-east-1_sa-east-1c',2, 'Y'),
	('ap-south-1','ap-south-1a','ap-south-1a','ap-south-1_ap-south-1a',1, 'Y'),
	('ap-south-1','ap-south-1b ','ap-south-1b ','ap-south-1_ap-south-1b ',2, 'Y'),
	('K8S_VERSION','1.9.10','1.9.10','K8S_VERSION_1.9.10',1, 'Y'),
	('K8S_VERSION','1.10.3','1.10.3','K8S_VERSION_1.10.3',2, 'Y'),
	('AWS_STORAGE_TYPE','gp2','1.10.3','AWS_STORAGE_TYPE_gp2',1, 'Y'),
	('AWS_STORAGE_TYPE','standard','1.10.3','AWS_STORAGE_TYPE_standard',2, 'Y'),
	('ACCOUNT_TYPE', 'CCO', 'Cocktail Cloud Online', 'Cocktail Cloud Online', 1, 'Y'),
	('ACCOUNT_TYPE', 'APP', 'Apps', 'Apps', 2, 'Y'),
	('ACCOUNT_TYPE', 'ENT', 'Enterprise', 'Enterprise.', 3, 'Y'),
	('ACCOUNT_TYPE', 'OEM', 'OEM', 'OEM', 4, 'Y'),
	('ACCOUNT_TYPE', 'CBE', 'Cube Engine', 'Cube Engine', 5, 'Y'),
	('CATALOG_TYPE', 'COCKTAIL', 'Cocktail', 'Cocktail type catalog - basic (Deprecated)', 0, 'N'),
	('CATALOG_TYPE', 'PACKAGE', 'Package', 'Package type catalog', 1, 'Y'),
	('CATALOG_TYPE', 'BUILD_PACK', 'Build Pack', 'Build Pack type catalog', 2, 'N'),
	('CATALOG_TYPE', 'SERVICE', 'Service', 'Service type catalog - CATALOG_SERVICE_TYPE child type exist', 3, 'Y'),
	('SERVICE_CATALOG', 'SYSTEM', 'System', 'Share catalogs within the system', 1, 'Y'),
	('SERVICE_CATALOG', 'WORKSPACE', 'Workspace', 'Share catalogs within the workspace', 2, 'Y'),
	('CURRENCY_CODE', 'KRW', '₩', 'Korean Won', 0, 'Y'),
	('CURRENCY_CODE', 'USD', '$', 'United States Dollar', 1, 'Y'),
	('CURRENCY_CODE', 'JPY', '¥', 'Japanese Yen', 2, 'Y'),
	('CURRENCY_CODE', 'CNY', '¥', 'Chinese Yuan', 3, 'Y'),
	('AUDIT_LOG_PERMISSION', 'DEVOPS', 'DevOps User\'s Permission', 'DevOps User\'s Permission', '1', 'Y'),
	('AUDIT_LOG_PERMISSION', 'SYSTEM', 'System User\'s Permission', 'System User\'s Permission', '2', 'Y'),
	('AUDIT_LOG_PERMISSION', 'ADMIN', 'Admin User\'s Permission', 'Admin User\'s Permission', '3', 'Y'),
	('AUDIT_LOG_GROUP', 'ACCOUNT', 'System Account', 'System Account', '1', 'Y'),
	('AUDIT_LOG_GROUP', 'WORKSPACE', 'Workspace', 'Workspace', '2', 'Y'),
	('AUDIT_LOG_GROUP', 'SERVICEMAPGROUP', 'Service Map Group', 'Service Map Group', '3', 'Y'),
	('AUDIT_LOG_GROUP', 'SERVICEMAP', 'Service Map', 'Service Map', '4', 'Y'),
	('AUDIT_LOG_GROUP', 'GROUP', 'Group', 'Group', '5', 'Y'),
	('AUDIT_LOG_GROUP', 'WORKLOAD', 'Workload', 'Workload', '6', 'Y'),
	('AUDIT_LOG_GROUP', 'SERVICESPEC', 'Kubernetes service', 'Kubernetes service', '7', 'Y'),
	('AUDIT_LOG_GROUP', 'INGRESS', 'Ingress', 'Ingress', '8', 'Y'),
	('AUDIT_LOG_GROUP', 'STORAGEVOLUME', 'Stroage Volume', 'Stroage Volume', '9', 'Y'),
	('AUDIT_LOG_GROUP', 'CONFIGMAP', 'ConfigMap', 'ConfigMap', '10', 'Y'),
	('AUDIT_LOG_GROUP', 'SECRET', 'Secret', 'Secret', '11', 'Y'),
	('AUDIT_LOG_GROUP', 'NETWORK', 'Network', 'Network', '12', 'Y'),
	('AUDIT_LOG_GROUP', 'PIPELINE', 'Pipeline', 'Pipeline', '13', 'Y'),
	('AUDIT_LOG_GROUP', 'BUILD', 'Build', 'Build', '14', 'Y'),
	('AUDIT_LOG_GROUP', 'CATALOG', 'Catalogue', 'Catalogue', '15', 'Y'),
	('AUDIT_LOG_GROUP', 'CLUSTER', 'Cluster', 'Cluster', '16', 'Y'),
	('AUDIT_LOG_GROUP', 'STORAGE', 'Stroage', 'Stroage', '17', 'Y'),
	('AUDIT_LOG_GROUP', 'USER', 'User', 'User', '18', 'Y'),
	('AUDIT_LOG_GROUP', 'ADDON', 'Add-on', 'Add-on', '19', 'Y'),
	('AUDIT_LOG_GROUP', 'ADMINUSER', 'Admin User', 'Admin User', '20', 'Y'),
	('AUDIT_LOG_GROUP', 'PACKAGE', 'Package', 'Package', '21', 'Y'),
	('USER_AUTH_TYPE', 'PLAIN', 'PLAIN ID/PW', 'ID, Password base Authentication', 1, 'Y'),
	('USER_AUTH_TYPE', 'AAD', 'Azure Active Directory', 'Azure ActiveDirectory base Authentication', 2, 'Y');
/*!40000 ALTER TABLE `codes` ENABLE KEYS */;


/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
